config/routes.rb
Rails.application.routes.draw do
  get 'book_comments/create'
  get 'book_comments/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get '/search', to: 'searches#search'
  resources :books, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources:book_comments,only:[:create,:destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member #あるユーザーがフォローしている人を全員を表示するためのルーティング on:memberとする事でルーティングにidを含ませることができる
    get :followers, on: :member #あるユーザーをフォローしてくれている人 フォロワーの一覧画面を表示させるためのルーティング
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_many :relationships, foreign_key: :follower_id #フォローする側からのhas_many
  has_many :followings, through: :relationships, source: :follower #あるユーザーがフォローしている人を全員取ってくる あるユーザをフォローしてくれているを全員持ってくる
  
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :followed_id #フォローされる側からのhas_many
  has_many :followers, through: :reverse_of_relationships, source: :follower #あるユーザーをフォローしてくれている人を全員取ってくる
  
  def is_followed_by?(user) #あるユーザーがあるユーザーにフォローされているか否かを判定するメソッド
    reverse_of_relationships.find_by(follower_id: user.id).present?
  end
 
  def already_favorited?(book)
    self.favorites.exists?(book_id: book.id)
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50}
  

  
  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
    @users = User.where.not(id: current_user.id) #ログインしている人以外のユーザー全部を取っていきたいので
  end
  
  def followings #あるユーザがフォローしている人全員を取得するアクションを定義する
    user = User.find(params[:id])
    @users = user.followings #このユーザーに結びついている、つまり、このuserがフォローしている人全員をとってくる事が出来る
  end
  
  def followers #あるユーザをフォローしている人全員を取得するアクションを定義する
    user = User.find(params[:id])
    @users = user.followers #このユーザをフォローしている人全員をとってくる事が出来る
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    @user.user_id = current_user.id
    if @user.save
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      flash[:alret] = "error"
    @users = User.all
    @user = current_user
    @book = Book.new
    render :index
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have created book successfully."
    redirect_to user_path(@user.id)
    else
    flash[:alret] = "error"
    render :edit
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="6"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= @user.followings.count %></td>
        <td>フォロワー数：<%= @user.followers.count %></td>
        <td>フォローする</td>
        <td><%= link_to 'Show', user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to @user.followings.count %> フォロー</th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to @user.followers.count %></th>
  </tr>
</table>
<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book, user: @user %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
        <% unless @user == current_user %>
            <% if @user.is_followed_by?(current_user) %>
              <%= link_to user_relationships_path(@user), method: :delete do %>
                <button class="btn btn-danger">フォロー解除</button>
              <% end %>
            <% else %>
            <%= link_to user_relationships_path(@user), method: :post do %>
              <button class="btn btn-primary">フォローする</button>
            <% end %>
          <% end %>
        <% end %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>