config/routes.rb
Rails.application.routes.draw do
  get 'book_comments/create'
  get 'book_comments/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get '/search', to: 'searches#search'
  resources :books, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources:book_comments,only:[:create,:destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member #あるユーザーがフォローしている人を全員を表示するためのルーティング on:memberとする事でルーティングにidを含ませることができる
    get :followers, on: :member #あるユーザーをフォローしてくれている人 フォロワーの一覧画面を表示させるためのルーティング
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :destroy, :update]
  
  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @booknew = Book.new
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      @user = current_user
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    redirect_to books_path unless @book.user == current_user
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    unless @user == current_user
    redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td>
          <% if current_user.already_favorited?(book) %>
            <%= link_to book_favorites_path(book), method: :delete do %>
              <i class = "fas fa-heart"></i>
            <% end %>
          <% else %>
            <%= link_to book_favorites_path(book), method: :post do %>
              <i class = "far fa-heart"></i>
            <% end %>
          <% end %>
          <%= book.favorites.count%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'layouts/errors', obj: @book %>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @booknew %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
              <% if @book.user == current_user %>
          <td><% if current_user.already_favorited?(@book) %>
                <%= link_to book_favorites_path(@book), method: :delete do %>
                  <i class = "fas fa-heart"></i>
              <% end %>
              
              <% else %>
              <%= link_to book_favorites_path(@book), method: :create do %>
                <i class = "far fa-heart"></i>
                <% end %>
              <% end %>
              <%= @book.favorites.count %>
          </td>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
              <% end %>
        </tr>
      </table>
      <table class='table'>
        <tbody>
             <% @book.book_comments.each do |book_comment| %>
          <tr>
             <td><%= image_tag book_comment.user.get_profile_image, size:"50x50" %></td>
             <td><%= book_comment.comment %></td>
             <td><%= link_to 'Destroy', book_book_comment_path(book_comment.book, book_comment), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          </tr>
                 <% end %>
        </tbody>
      </table>
               <%= form_with model:[@book,@book_comment] do |f| %>
               <div class="form-group">
                 <%= f.text_area :comment %>
               </div>
               <div class="form-group">
                 <%= f.submit "送信" %>
               </div>
               <% end %>
    </div>
  </div>
</div>